### ISSUE TITLE
Route::model binding causing other package route broken

### ISSUE THREAD

**Issue by huiyang** [artkonekt/concord#11] opened 2020-08-25 14:05 UTC
I used vanilo/product package which bound the router parameter "{product}" to Vanilo\Product\Models\Product,
and I have another package which have route like this:

```
Route::get("products/{product}", function(\Example\Models\Product $product) {

});
```

it will always return empty $product as its class is not matched with the bound model class.

Is this explicit binding necessary? or implicit binding will be sufficient?

Thanks in advance.

**Comment by fulopattila122** [comment] 2020-08-25 15:24
I'm not sure if this is a Concord related question, but since I'm the lead developer of both Concord and Vanilo, let's ignore this :smile: 

1. Is `Example\Models\Product` a class or an interface? Is it an Eloquent model?
2. What's the output of `php artisan concord:models`?

**Comment by huiyang** [comment] 2020-08-25 18:46
Thanks for your reply.

1) It is a Eloquent model.
2) 
![image](https://user-images.githubusercontent.com/517651/91214417-9cf0ae00-e745-11ea-9efb-3fa61dde927c.png)

You may try to add a route in vanilophp/demo as this:

```
Route::get("test-products/{product}", function(\App\Models\Product $product) {
    dd($product, $product->id); // This will return null
});
```

and this

```
Route::get("test-products2/{product2}", function(\App\Models\Product $product2) {
    dd($product2, $product2->id); // This will return an \App\Models\Product object
});
```

Changing the parameter name from "{product}" to "{product2}" will solve the issue, but i can't simply change the name, as it is another third party package.

**Comment by huiyang** [comment] 2020-08-25 19:05
Anyway, I have this temporary fix for my own project, but I don't pull request as this seem like a breaking change. (Although just one word is changed 😄 ) 

https://github.com/antwebstudio/concord/commit/0ba1de737a601948fca4057ac4687068db730558

**Comment by fulopattila122** [comment] 2020-08-26 15:46
We still need to find the root cause, I'm not sure if it's related to Concord.
Is `App\Models\Product` related to Vanilo Products? Is it maybe extending it?

**Comment by huiyang** [comment] 2020-08-27 04:17
For my case, it is not extending Vanilo product model, but yes, it is implementing Vanilo product Contract (interface).
But there may be other cases which are not related to Vanilo product.

```
// My case:
class Product extends \Fusion\Models\Collections\Product implements \Vanilo\Product\Contracts\Product
```

anyway, this issue is still there for both case whether the App\Models\Product is related to Vanilo product, as Laravel will always threated the model as a totally different model unrelated to Vanilo product, in route resolving for both case. (that is why Laravel binding a empty null product to the route)

```
Route::get("test-products/{product}", function(\App\Models\ProductNonRelatedToVaniloProduct $product) {
    dd($product, $product->id); // This will return null
});
```

```
Route::get("test-products/{product}", function(\App\Models\ExtendedVaniloProduct $product) {
    dd($product, $product->id); // This will alo return null
});
```

both are returninng null value as {product} is bound to \Vanilo\Product\Contracts\Product in vanilo/product.
and yet, rebinding the route model to \App\Models\Product won't help as some route is binding to \Fusion\Models\Collections\Product  (\App\Models\Product extending to \Fusion\Models\Collections\Product )

and, Laravel don't allow unbinding the binding.

So, I think there should be some way to switch off the auto route model binding, maybe in the module configuration?

**Comment by fulopattila122** [comment] 2020-08-27 07:11
You need to tell the system if you want to replace the product model, see https://vanilo.io/how-to/use-custom-models-in-your-application

```php
// app/Providers/AppServiceProvider.php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Vanilo\Product\Contracts\Product as ProductContract;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->app->concord->registerModel(
            ProductContract::class, \App\Models\Product::class
        );
    }
}
```

**Comment by huiyang** [comment] 2020-08-27 07:37
Yes, i did register the model, so now the first route below is working, but the second route do not.
Because by having registerModel(ProductContract::class, \App\Models\Product::class);

Concord do: 
```
Route:model('product', \App\Models\Product::class); // This caused the second route below not working
```
This caused the second route below not working.

```
Route::get("test-products/{product}", function(\App\Models\Product $product) {
    dd($product, $product->id); // This will return product model
});
```
```
Route::get("test-products/{product}", function(\Fusion\Models\Product $product) {
    dd($product, $product->id); // This will return null
});
```

**Comment by fulopattila122** [comment] 2020-08-27 07:53
So Concord should not do this https://laravel.com/docs/7.x/routing#explicit-binding under the hood, right?

**Comment by fulopattila122** [comment] 2020-08-27 07:56
https://github.com/artkonekt/concord/blob/master/src/Concord.php#L134

Does setting the 3rd parameter to false help?

```php
$this->app->concord->registerModel(
    ProductContract::class, \App\Models\Product::class, false
);
```

**Comment by huiyang** [comment] 2020-08-27 09:09
> So Concord should not do this https://laravel.com/docs/7.x/routing#explicit-binding under the hood, right?

Maybe, or maybe add a setting under module? like the setting to exclude migration load



> https://github.com/artkonekt/concord/blob/master/src/Concord.php#L134
> 
> Does setting the 3rd parameter to false help?
> 
> ```
> $this->app->concord->registerModel(
>     ProductContract::class, \App\Models\Product::class, false
> );
> ```

Not really, as this line
https://github.com/vanilophp/framework/blob/5f5ec185c9afe4c1023c6213314cad31b616595f/src/Providers/ModuleServiceProvider.php#L89
will already bind the route model to \Vanilo\Framework\Models\Product

**Comment by fulopattila122** [comment] 2020-08-27 09:50
>  add a setting under module?

That's exactly what I was thinking about to add. Added it to my schedule for tomorrow.
It's gonna be in 1.7 - to be released in the next days.

Thanks for taking the effort and guiding me through this issue!

**Comment by huiyang** [comment] 2020-08-27 11:00
Thanks to your effort and your module as well! I like it as it is so modular, hopefully I can contribute to your code in future (especially the vanilo modules), but let me enhance my code quality before that, currently my code is not really modular yet 😆

**Closed** 2020-08-31 10:36 UTC
Labels: question

**Comment by fulopattila122** [comment] 2020-08-31 10:41
Update Concord to v1.7 and use the `register_route_models` in `config/concord.php` to disable route model automatic registration.

See: https://konekt.dev/concord/1.7/routes#route-model-bindings

**Comment by fulopattila122** [comment] 2020-11-29 13:52
Hi @huiyang just a funny update: I had an issue today, where the solution was to disable `register_route_models` - the feature you've requested with this issue.

When I realized, I thought I'm so grateful to you and for this issue, otherwise, it would've taken hours for me to figure it out :ok_hand: 

So thank you! :wink: 

Ps.: Most probably, Concord 2.x will not do this implicit binding at all.

**Comment by huiyang** [comment] 2020-12-03 17:49
greate to hear that!

you actually helped me a lot for having vanilo ecommerce open source.

Thanks too!
